### ISSUE TITLE
How to use `batteryml` command line tool in Windows?

### ISSUE THREAD

**Issue by yunqi90** [microsoft/BatteryML#21] opened 2023-11-03 01:52 UTC
Download the raw data and run the two commands used in the preprocessing script:
I type in the Command Prompt and it says 'batteryml' is not recognized as an internal or external command, operable program or batch file.
Entering in Windows PowerShell executes successfully but without any action and result. Just skipped it.
What is the problem?

**Comment by fingertap** [comment] 2023-11-03 01:56
We did not test our tool in Windows. The command `batteryml` is installed by Python using the `setup.py`. Can you provide more information of how you install the package and your Python environment?

**Comment by yunqi90** [comment] 2023-11-03 02:05
Hello, where do you enter the command specifically? I entered it in CMD in Windows.
![image](https://github.com/microsoft/BatteryML/assets/149743642/d5a345be-61b6-4577-a726-f432e553ffde)
![image](https://github.com/microsoft/BatteryML/assets/149743642/47c5c5c0-04a7-4cfd-b696-679e1bcfc56d)

**Comment by fingertap** [comment] 2023-11-03 02:15
You should use windows powershell and use `batteryml` instead of `BatteryML`. The command line is case-sensitive.

**Comment by yunqi90** [comment] 2023-11-03 02:21
大小写是一样的效果，都没有起任何作用，路径也已经添加到系统变量中
![image](https://github.com/microsoft/BatteryML/assets/149743642/ee631445-610b-4d23-b12f-681e3364d20b)

**Comment by fingertap** [comment] 2023-11-14 02:23
Can you share the output of `echo %PATH%` in the command prompt? Make sure that the `Scripts` folder is in your PATH, which holds the custom scripts installed using `setup.py`.

**Comment by christosiraklis** [comment] 2023-11-23 13:29
Same problem here. Working on Windows 10. I have found the batteryml file in the bin folder as well as in my python environment folder. I have tried using both Paths but none worked. Any solution?

**Comment by fingertap** [comment] 2023-11-23 13:31
This error indicates the script `batteryml` is not found. I will test on Windows 10. Please stay tuned.

**Comment by fingertap** [comment] 2023-11-23 14:14
After some investigation, I made this work under Windows. The cause was the `setup.py`. We initially depended on the shebang line, e.g. `#!/usr/bin/python`, in `bin/batteryml` to work in Linux. Under Windows, pip cannot determine the correct entry point for this script. I got two solutions to this issue.

1. (Quick) Use bash under windows. For example, if you installed git, there may be a `Git Bash`, which you may find in your option menu after right click.
2. I will create a PR later to fully address this issue. The key is to use `entry_points` in `setup.py`.

**Comment by fingertap** [comment] 2023-11-23 15:37
#23 should address this issue.

**Comment by fingertap** [comment] 2023-11-24 02:29
Close this as #23 is merged. Feel free to reopen this if any further problems encountered.

**Closed by fingertap** 2023-11-24 02:29 UTC
